Discover
Aadarsh805/100daysofcode-tracker pull request #67
Opened 2023-02-19 12:50 UTC by Somidh

2023-02-19 20:37 UTC, Aadarsh805 requested changes
something like this

![Group 42 (8)](https://user-images.githubusercontent.com/95094057/219973895-33494192-9455-4d8b-9095-53d26de2581b.png)

2023-02-21 19:03 UTC, Somidh commented
Requested pr for the changes

2023-02-22 08:29 UTC, Aadarsh805 requested changes
Please remove `supabase.ts` from the commit

2023-03-06 23:41 UTC, Aadarsh805 commented
@Somidh

2023-03-07 06:16 UTC, closed without merging